function tscol =  addts(bmname, struct)
    tscol = tscollection(struct.Time,'Name', bmname);
    tscol = addts(tscol,struct.Ambient_Temp0, 'Ambient_Temp0');
    tscol = addts(tscol,struct.Ambient_Temp1, 'Ambient_Temp1');
    tscol = addts(tscol,struct.CPU_0_Temp, 'CPU_0_Temp');
    tscol = addts(tscol,struct.CPU_1_Temp, 'CPU_1_Temp');
    tscol = addts(tscol,struct.HT1Scaled, 'HT1Scaled');
    tscol = addts(tscol,struct.HT2Scaled, 'HT2Scaled');
    tscol = addts(tscol,struct.cmiss_core0_scaled, 'cmiss_core0_scaled');
    tscol = addts(tscol,struct.cmiss_core1_scaled, 'cmiss_core1_scaled');
    tscol = addts(tscol,struct.cmiss_core2_scaled, 'cmiss_core2_scaled');
    tscol = addts(tscol,struct.cmiss_core3_scaled, 'cmiss_core3_scaled');
    tscol = addts(tscol,struct.disk_read_kbytes, 'disk_read_kbytes'); 
    tscol = addts(tscol,struct.disk_write_kbytes, 'disk_write_kbytes');
    tscol = addts(tscol,struct.Axial_Fan_0, 'Axial_Fan_0');
    tscol = addts(tscol,struct.Axial_Fan_1, 'Axial_Fan_1');
    tscol = addts(tscol,struct.Blower_Fan_0, 'Blower_Fan_0');
    tscol = addts(tscol,struct.Blower_Fan_1, 'Blower_Fan_1');
