function importcsv(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 16-Aug-2008 10:36:13

% Import the file
newData1 = importdata(fileToRead1);

% Break the data up into a new structure with one field per column.
colheaders = genvarname(newData1.colheaders);
for r = 1:length(colheaders)
    dataByColumn1.(colheaders{r}) = newData1.data(:, r);
    % Convert any NaNs to 0 
    for c = 1:length(dataByColumn1.(colheaders{r}))
        n = dataByColumn1.(colheaders{r})(c);
        if isnan(n)
            dataByColumn1.(colheaders{r})(c) = 0;
        end
    end
end

% Create new variables in the base workspace from those fields.
vars = fieldnames(dataByColumn1);
for i = 1:length(vars)
    assignin('caller', vars{i}, dataByColumn1.(vars{i}));
end

