fprintf('\\caption{Analysis of residuals:}\n');
fprintf('bm & mean & median & std\\\n');
bzip2.estimates = estimates(b,bzip2);
bzip2.residuals = abs(bzip2.estimates - bzip2.ProcPwr);
bzip2.rstats = datastats(bzip2.residuals);
fprintf('bzip2&& %10.6f &&%10.6f &&%10.6d\\\n',...
    bzip2.rstats.mean, ...
    bzip2.rstats.median, ...
    bzip2.rstats.std);

cactusadm.estimates = estimates(b,cactusadm);
cactusadm.residuals = abs(cactusadm.estimates - cactusadm.ProcPwr);
cactusadm.rstats = datastats(cactusadm.residuals);
fprintf('cactusadm &%10.6f &%10.6f &%10.6d\\\n',...
    cactusadm.rstats.mean, ...
    cactusadm.rstats.median, ...
    cactusadm.rstats.std);

gromac.estimates = estimates(b,gromac);
gromac.residuals = abs(gromac.estimates - gromac.ProcPwr);
gromac.rstats = datastats(gromac.residuals);
fprintf('gromac &%10.6f &%10.6f &%10.6d\\\n',...
    gromac.rstats.mean, ...
    gromac.rstats.median, ...
    gromac.rstats.std);

lbm.estimates = estimates(b,lbm);
lbm.residuals = abs(lbm.estimates - lbm.ProcPwr);
lbm.rstats = datastats(lbm.residuals);
fprintf('lbm &%10.6f& %10.6f& %10.6d\\\n',...
    lbm.rstats.mean, ...
    lbm.rstats.median, ...
    lbm.rstats.std);

leslie3d.estimates = estimates(b,leslie3d);
leslie3d.residuals = abs(leslie3d.estimates - leslie3d.ProcPwr);
leslie3d.rstats = datastats(leslie3d.residuals);
fprintf('leslie3d &%10.6f& %10.6f& %10.6d\\\n',...
    leslie3d.rstats.mean, ...
    leslie3d.rstats.median, ...
    leslie3d.rstats.std);

mcf.estimates = estimates(b,mcf);
mcf.residuals = abs(mcf.estimates - mcf.ProcPwr);
mcf.rstats = datastats(mcf.residuals);
fprintf('mcf& %10.6f& %10.6f\t &%10.6d\\\n',...
    mcf.rstats.mean, ...
    mcf.rstats.median, ...
    mcf.rstats.std);

omnetpp.estimates = estimates(b,omnetpp);
omnetpp.residuals = abs(omnetpp.estimates - omnetpp.ProcPwr);
omnetpp.rstats = datastats(omnetpp.residuals);
fprintf('omnetpp& %10.6f &%10.6f &%10.6d\\\n',...
    omnetpp.rstats.mean, ...
    omnetpp.rstats.median, ...
    omnetpp.rstats.std);

perlbench.estimates = estimates(b,perlbench);
perlbench.residuals = abs(perlbench.estimates - perlbench.ProcPwr);
perlbench.rstats = datastats(perlbench.residuals);
fprintf('perlbench& %10.6f& %10.6f& %10.6d\\\n',...
    perlbench.rstats.mean, ...
    perlbench.rstats.median, ...
    perlbench.rstats.std);
