function [temphat err] =  taddest(actual, struct,bhat,lc)
A=[ones(size(struct.Ambient_Temp0)) ...
    struct.Ambient_Temp0 ...
    struct.Ambient_Temp1 ...
    struct.HT1Scaled ...
    struct.HT2Scaled ...
    struct.cmiss_core0_scaled ...
    struct.cmiss_core1_scaled ...
    struct.cmiss_core2_scaled ...
    struct.cmiss_core3_scaled ...
    struct.disk_read_kbytes ... 
    struct.disk_write_kbytes ...
    struct.Axial_Fan_0 ...
    struct.Axial_Fan_1 ...
    struct.Blower_Fan_0 ...
    struct.Blower_Fan_1];

temphat = A*bhat;
err = abs(actual - temphat);
plot(struct.Time,actual,lc);
