#
# File:	 	Makefile
# Author:	Adam Lewis
# Copyright:	(c)2006, The University of Louisiana at Lafayette, All rights reserved.
#
CFLAGS=-g -DSOLARIS
INSTDEST=/opt/wattsup
#CC=gcc
#LFLAGS = lstdc++
#CFLAGS="-O2 -Wall -Wno-format"
#INSTDEST = /usr/local/bin
#LFLAGS = -lpq

all: 

clean:

install:
	mkdir -p $(INSTDEST)
	cp runtest.sh gatheripmi.sh gatherpmc.sh $(INSTDEST)
