#+TITLE:     gettempfromproc.org
#+AUTHOR:    Adam Lewis
#+EMAIL:     awl8049@canmac03.cacs.louisiana.edu
#+DATE:      2011-03-29 Tue
#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT: 
* How to read the temperature directly from the processor
** The sysctl kernel interface
*** Kernel exposes information to the user via sysctl(3) system call
The sysctl(3) pattern appears to require pairs of calls to the API:
call first to get the size of the data and then call again to get
the actual data.  In the first call, send a point to an allocated
size_t where the API will tell you how much space to allocate. Then
use this information to allocate a buffer that will contain the
data. Then call the function again, passing a pointer to this data
and the size from the first call.
*** Temperature format     
For both the AMD and Intel temp monitors, you will be returned an
int32_t with the current reading from the thermal diode in units of
0.1K.
** Two kernel modules need to be loaded into the kernel
*** For AMD processors, need to load the amdtemp module
Adds entries in the sysctl data in the format
#+BEGIN_EXAMPLE
dev.amdtemp.<CPU>.sensor<x>.core<y>
#+END_EXAMPLE
There will be entries for each CPU.  All entries that I've seen to date
have a maximum of two sensors.   Each sensor will have an entry for each
core.  At least for the AMD K8 that's in the Sun X2200, only sensor0 has
valid information.
*** For Intel processors, need to load the coretemp module
Add entries in the sysctl data in the format
#+BEGIN_EXAMPLE
dev.cpu.<logicalCPU>.temperature
#+END_EXAMPLE
On the Intel processor, each core is considered a logical CPU.  
* Issues
1) For Intel processors, how do you differentiate between physical CPUS?
2) Do you ever get useful information from anything other than sensor0
   for AMD processors?
